# Generated by Django 3.2.5 on 2021-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_menu_title_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=80)),
                ('first_title_fa', models.CharField(max_length=80)),
                ('second_title', models.CharField(max_length=80)),
                ('second_title_fa', models.CharField(max_length=80)),
                ('background', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('title_fa', models.CharField(max_length=60)),
            ],
        ),
    ]
