# Generated by Django 3.2.5 on 2021-07-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerbutton',
            name='link',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
    ]
