# Generated by Django 3.2.5 on 2021-07-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_headerbutton_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text_fa',
            field=models.TextField(default='متن طولانی و بزرگ فارسی '),
            preserve_default=False,
        ),
    ]
