# Generated by Django 3.2.5 on 2021-08-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='work_duration_date',
            field=models.CharField(default='15 september 2015 - 5 august 2021', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='work_duration_date_fa',
            field=models.CharField(default='شهریور 97 تا ابان 99', max_length=200),
            preserve_default=False,
        ),
    ]
