# Generated by Django 3.2.5 on 2021-08-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210803_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_title', models.CharField(max_length=80)),
                ('study_grade', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('study_duration_date', models.CharField(max_length=200)),
                ('university_title_fa', models.CharField(max_length=80)),
                ('study_grade_fa', models.CharField(max_length=60)),
                ('description_fa', models.TextField()),
                ('study_duration_date_fa', models.CharField(max_length=200)),
            ],
        ),
    ]
