# Generated by Django 3.2.5 on 2021-08-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('title_fa', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('description_fa', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('link', models.URLField()),
            ],
        ),
    ]
