# Generated by Django 3.2.5 on 2021-08-04 01:59

from django.db import migrations, models
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=35)),
                ('icon', faicon.fields.FAIconField(max_length=50)),
            ],
        ),
    ]
